name: Nightly

on:
  push:
    branches: [ acrylic-new ]
    paths:
    - 'src/**'
    - 'scripts/**'
    - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js v16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Pack base asar
      run: |
        npm i -g asar
        sed -i -e "s/nightly/nightly-$(git rev-parse HEAD | cut -c 1-7)/" src/index.js
        node scripts/strip.js
        npx asar pack src app.asar

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: built-asar
        path: app.asar
        retention-days: 1

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Retrieve artifact
      uses: actions/download-artifact@v3
      with:
        name: built-asar
        path: artifact

    - name: Extract artifact
      run: |
        cp artifact/app.asar .

    - name: GitHub Release
      run: |
        git tag -d nightly || true
        git push origin --delete nightly || true
        git tag nightly
        git push origin nightly
        curl -L -o old.asar "https://github.com/touanu/OpenAsar/releases/download/nightly/app.asar"
        gh release delete ${{ env.VERSION }} -y || true
        gh release create ${{ env.VERSION }} -t "Nightly" -n "$(bash scripts/nightlyNotes.sh)" ${{ env.FILES }}
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        VERSION: 'nightly'
        FILES: app.asar
